jwt_verification
codal-umistri/jwt_verification pull request #1
Opened 2024-03-01 05:56 UTC by codal-umistri

2024-03-01 06:04 UTC, het-codal commented on dbconfig/dbconfig.js
> +  database: "User",
Take all DB from env

2024-03-01 06:06 UTC, het-codal commented on sql/querys.js
> +        console.log(results);
remove console logs or comment it

2024-03-01 06:08 UTC, het-codal commented on validations/Validator.js
> +exports.validatelogininputs = (req, res, next) => {
make this function name as validateLoginInputs

2024-03-01 06:09 UTC, het-codal commented on validations/Validator.js
> +exports.validateemail = (req, res, next) => {
Make function name validateEmail

2024-03-01 06:10 UTC, het-codal commented on validations/Validator.js
> +  if (!validator.isEmail(email)) {
make use of common function for validating email

2024-03-01 06:11 UTC, het-codal commented on validations/Validator.js
> +    return res.status(400).json({ message: "Please fill in all fields" });
make sure only one return statement should be their take variable and set message and on base of that return error

2024-03-01 06:12 UTC, het-codal commented on .gitignore
> +Routes/noteRoute.js
if you are not using routes file make sure you remove them instade of ignore also create .env.example for .env file only variable should be their

2024-03-01 06:14 UTC, het-codal requested changes

2024-03-01 06:14 UTC, het-codal commented on Routes/Route.js
> +router.post("/registration", validateInput, Registration);
make sure all method routs (GET, POST, PUT, DELETE)  should be in same manner

2024-03-01 06:15 UTC, het-codal commented
Also Update readme file and steps for setup, description tech used

2024-03-01 11:05 UTC, codal-umistri commented on validations/Validator.js
> +    return res.status(400).json({ message: "Please fill in all fields" });
is this correct way :- 

  confirm_password === "undefined"
) {
  errorMessage = "Please fill in all fields";
}

if (errorMessage) {
  return res.status(400).json({ message: errorMessage });
}

2024-03-04 11:02 UTC, het-codal approved these changes

2024-03-05 07:41 UTC, codal-apatel commented on controller/NoteController.js
> +    await getAllNote("NOTES", (error, result) => {
Remove await if not needed as you are using callbacks.

2024-03-05 09:41 UTC, codal-apatel commented on controller/NoteController.js
> +    await getAllNote("NOTES", (error, result) => {
Okay. Change callbacks to promise (async, await).

2024-03-06 09:21 UTC, codal-apatel approved these changes

2024-03-06 09:22 UTC, merged